version: '2'
services:
  psql:
    image: postgres:9.6
    container_name: ifme_pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
  app:
    build: .
    container_name: ifme_app
    ports:
      - "3000:3000"
    depends_on:
      - psql
    environment:
      - PSQL_USERNAME=postgres
      - PSQL_HOST=psql
